name: Publish
on:
 release:
  types: [published]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: checkout
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 5.0.x
      
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      shell: bash
      run: |
          tag=$(git describe --tags --abbrev=0)
          release_name="ProjectExtractor-$tag"

          #build everything
          dotnet publish src/Project-Extractor/ProjectExtractor/ProjectExtractor.csproj --framework net5.0-windows --runtime win-x64 -c Release -o "$release_name"

          #pack files
          7z a -tzip "${release_name}.zip" "./${release_name}/*"

          #delte output directoty
          rm -r "$release_name"
    - name: Publish
      uses: softprops/action-gh-release@v1
      with:
       files: "ProjectExtractor*"
      env:
       GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    
