//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseCleaner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DatabaseCleaner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT &quot;CustomerID&quot;, &quot;CompanyName&quot; FROM Customers.
        /// </summary>
        internal static string GetAllCustomers {
            get {
                return ResourceManager.GetString("GetAllCustomers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	COUNT(*) AS  duplicates ,&quot;TITLE&quot;,&quot;Period&quot;,&quot;CompanyName&quot;,&quot;PROJECT&quot;,&quot;STARTDATE&quot;,&quot;ENDDATE&quot;,&quot;HOURS&quot;,&quot;TYPE&quot;,&quot;SOFTWARE&quot;,&quot;DESC&quot;,&quot;TECHNEW&quot;,&quot;TECH&quot;,&quot;PROB&quot;,&quot;OPLO&quot;,&quot;METH&quot;,&quot;ZELF&quot;,&quot;PRIN&quot;,&quot;Opmerkingen&quot;,&quot;Vragen Senter&quot;,&quot;Afgewezen&quot;
        ///FROM ((WBSO_P  
        ///	INNER JOIN &quot;Periode&quot; ON [WBSO_P].[Periode] = [Periode].[PeriodID])
        ///	INNER JOIN &quot;Customers&quot; ON [WBSO_P].[CustomerID] = [Customers].[CustomerID])
        ///GROUP BY 
        ///	 &quot;TITLE&quot;,&quot;Period&quot;,&quot;CompanyName&quot;,&quot;STARTDATE&quot;,&quot;ENDDATE&quot;,&quot;PROJECT&quot;,&quot;HOURS&quot;,&quot;TYPE&quot;,&quot;SOFTWARE&quot;,&quot;DESC&quot;,&quot;TECHNEW&quot;,&quot;TEC [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetProjects {
            get {
                return ResourceManager.GetString("GetProjects", resourceCulture);
            }
        }
    }
}
